"""Koast site data — add a city here and re-run generate.py."""

BOOK = "https://customer.moovs.app/koast/request/new"
PHONE = "(650) 880-6514"
SMS = "sms:6508806514"
EMAIL = "reserve@koastride.com"

FLEET = [
    dict(img="fleet-sedan.jpg", name="Business Sedan",
         amen=["Still & sparkling water","USB-C & Lightning chargers","Free airport wait time"],
         sub="Mercedes E-Class, BMW 5 Series, Cadillac CT5, or similar",
         tags=["3 passengers", "3 bags", "Airport wait incl."],
         price="Flat rate, all-inclusive", cta="Book"),
    dict(img="fleet-business-suv.jpg", name="Business SUV",
         amen=["Still & sparkling water","USB-C & Lightning chargers","Free airport wait time"],
         sub="Chevrolet Suburban, Ford Expedition, GMC Yukon, or similar",
         tags=["7 passengers", "7 bags", "Airport wait incl."],
         price="Flat rate, all-inclusive", cta="Book"),
    dict(img="fleet-first-class-suv.jpg", name="First-Class SUV",
         amen=["Second-row captain seats with extra legroom","Still & sparkling water","USB-C & Lightning chargers"],
         sub="Cadillac Escalade ESV, Lincoln Navigator L, GMC Yukon Denali",
         tags=["6 passengers", "6 bags", "Airport wait incl."],
         price="Flat rate, all-inclusive", cta="Book", badge="★ Captain Seats"),
    dict(img="fleet-sprinter.jpg", name="Executive Sprinter Van",
         amen=["Onboard entertainment","Water & device chargers","Room for 14 suitcases"],
         sub="Mercedes-Benz Executive Sprinter",
         tags=["14 passengers", "14 bags", "Groups & offsites"],
         price="Custom quote", cta="Get Quote"),
    dict(img="fleet-mid-party-bus.jpg", name="Mid-Size Party Bus",
         amen=["Spacious open cabin","Built for events & celebrations","Room for 15 suitcases"],
         sub="Groups, events & celebrations",
         tags=["20 passengers", "15 bags", "Events"],
         price="Custom quote", cta="Get Quote"),
    dict(img="fleet-large-party-bus.jpg", name="Large Party Bus",
         amen=["Seats up to 32 comfortably","Weddings & large events","Room for 22 suitcases"],
         sub="Weddings, big events & large groups",
         tags=["32 passengers", "22 bags", "Weddings"],
         price="Custom quote", cta="Get Quote"),
]

CITIES = {
  # ---------------- BAY AREA (home base) ----------------
  "san-francisco": dict(region="bay", name="San Francisco", short="SF",
    blurb="From the Financial District to the Presidio — professional chauffeured rides anywhere in the city, 24/7.",
    hoods="Financial District, SoMa, Nob Hill, Pacific Heights, the Marina, Mission Bay, and the Presidio",
    airports="SFO (25 min), OAK (30 min), SJC (50 min)",
    routes=[("SFO Airport → Downtown SF","25–35 min"),("San Francisco → Napa Valley","1.5 hr"),
            ("San Francisco → Silicon Valley","45–60 min"),("OAK Airport → San Francisco","30–40 min")],
    faq_extra=("Do you serve all San Francisco neighborhoods?",
               "Yes — every neighborhood, from the Embarcadero to Ocean Beach, plus hotels, offices, hospitals, and event venues citywide.")),
  "san-jose": dict(region="bay", name="San Jose", short="San Jose",
    blurb="Silicon Valley's most reliable black car service — executive travel for the tech capital, 24/7.",
    hoods="Downtown San Jose, North San Jose, Santana Row, Willow Glen, and the Berryessa district",
    airports="SJC (10 min), SFO (45 min), OAK (40 min)",
    routes=[("SJC Airport → Downtown San Jose","10–15 min"),("San Jose → San Francisco","50–70 min"),
            ("San Jose → Palo Alto / Menlo Park","25–35 min"),("SFO Airport → San Jose","45–60 min")],
    faq_extra=("Do you provide rides for tech company events and offsites?",
               "Yes — we regularly coordinate executive transport, team offsites, and investor visits across Silicon Valley, including multi-vehicle bookings.")),
  "oakland": dict(region="bay", name="Oakland", short="Oakland",
    blurb="Premium chauffeured rides across Oakland and the East Bay — airport transfers, events, and corporate travel.",
    hoods="Downtown Oakland, Jack London Square, Rockridge, Montclair, and Lake Merritt",
    airports="OAK (15 min), SFO (35 min), SJC (50 min)",
    routes=[("OAK Airport → Downtown Oakland","15–20 min"),("Oakland → San Francisco","25–40 min"),
            ("Oakland → Berkeley","15–20 min"),("SFO Airport → Oakland","35–50 min")],
    faq_extra=("Do you serve Berkeley and the rest of the East Bay?",
               "Yes — Berkeley, Alameda, Emeryville, Walnut Creek, Pleasanton, and the entire East Bay are within our standard service area.")),
  "palo-alto": dict(region="bay", name="Palo Alto", short="Palo Alto",
    blurb="Executive black car service for the heart of Silicon Valley — Stanford, Sand Hill Road, and beyond.",
    hoods="University Avenue, Stanford, Sand Hill Road, Midtown, and the Stanford Research Park",
    airports="SFO (30 min), SJC (25 min), OAK (45 min)",
    routes=[("SFO Airport → Palo Alto","30–40 min"),("Palo Alto → San Francisco","45–60 min"),
            ("SJC Airport → Palo Alto","25–35 min"),("Palo Alto → Menlo Park / Sand Hill Rd","10–15 min")],
    faq_extra=("Do you handle VC and executive meeting schedules?",
               "Yes — many of our riders are executives and investors with packed calendars. Your chauffeur waits between meetings, and hourly charters are available.")),

  # ---------------- NATIONWIDE ----------------
  "new-york": dict(region="national", name="New York City", short="NYC",
    blurb="Professional chauffeured black car service across Manhattan, Brooklyn, and the greater New York area.",
    hoods="Midtown, the Financial District, the Upper East & West Sides, Brooklyn, and Long Island City",
    airports="JFK (45–75 min), LGA (25–40 min), EWR (40–60 min)",
    routes=[("JFK Airport → Manhattan","45–75 min"),("LGA Airport → Midtown","25–40 min"),
            ("EWR Airport → Manhattan","40–60 min"),("Manhattan → The Hamptons","2–3 hr")],
    faq_extra=("Do you cover all three NYC-area airports?",
               "Yes — JFK, LaGuardia, and Newark, with flight tracking and curbside pickup at all terminals.")),
  "los-angeles": dict(region="national", name="Los Angeles", short="LA",
    blurb="Black car service across LA — from LAX to Beverly Hills, Santa Monica to Downtown, handled professionally.",
    hoods="Beverly Hills, Santa Monica, West Hollywood, Downtown LA, Culver City, and the Valley",
    airports="LAX (varies by area), BUR (20–40 min), SNA (45–75 min)",
    routes=[("LAX Airport → Beverly Hills","30–50 min"),("LAX Airport → Downtown LA","30–60 min"),
            ("BUR Airport → Hollywood","20–30 min"),("Los Angeles → Orange County","1–1.5 hr")],
    faq_extra=("Can you handle studio and production schedules?",
               "Yes — we work with shifting call times and multi-stop days. Hourly charters keep a chauffeur dedicated to your schedule.")),
  "chicago": dict(region="national", name="Chicago", short="Chicago",
    blurb="Chauffeured rides across Chicagoland — O'Hare and Midway transfers, the Loop, and the North Shore.",
    hoods="The Loop, River North, the Gold Coast, West Loop, Lincoln Park, and the Magnificent Mile",
    airports="ORD (35–60 min), MDW (25–40 min)",
    routes=[("ORD Airport → The Loop","35–60 min"),("MDW Airport → The Loop","25–40 min"),
            ("Chicago → Evanston / North Shore","30–50 min"),("ORD Airport → Schaumburg","20–30 min")],
    faq_extra=("Do you serve the suburbs?",
               "Yes — Naperville, Schaumburg, Evanston, Oak Brook, and the greater Chicagoland area.")),
  "miami": dict(region="national", name="Miami", short="Miami",
    blurb="Black car service for Miami and South Florida — airport transfers, Brickell to South Beach, events and nights out.",
    hoods="Brickell, Downtown, South Beach, Wynwood, Coral Gables, and Miami Beach",
    airports="MIA (15–30 min), FLL (35–50 min)",
    routes=[("MIA Airport → South Beach","20–30 min"),("MIA Airport → Brickell","15–25 min"),
            ("FLL Airport → Miami","35–50 min"),("Miami → Palm Beach","1.5 hr")],
    faq_extra=("Do you serve Fort Lauderdale and Palm Beach?",
               "Yes — the full South Florida corridor, including FLL and PBI airports, Boca Raton, and Palm Beach.")),
  "las-vegas": dict(region="national", name="Las Vegas", short="Vegas",
    blurb="Chauffeured Vegas rides — Harry Reid airport transfers, the Strip, conventions, and group events.",
    hoods="The Strip, Downtown, Summerlin, Henderson, and the Convention Center district",
    airports="LAS (10–20 min)",
    routes=[("LAS Airport → The Strip","10–20 min"),("LAS Airport → Downtown","15–25 min"),
            ("The Strip → Red Rock Canyon","30–40 min"),("Las Vegas → Henderson","20–30 min")],
    faq_extra=("Do you handle convention and group transportation?",
               "Yes — CES, conferences, and group events are a specialty. Sprinters and buses move teams between venues seamlessly.")),
  "dallas": dict(region="national", name="Dallas", short="Dallas",
    blurb="Executive black car service across the Dallas–Fort Worth metroplex — DFW transfers, Uptown, Plano, and Frisco.",
    hoods="Uptown, Downtown, Highland Park, Las Colinas, Plano, and Frisco",
    airports="DFW (25–40 min), DAL (15–25 min)",
    routes=[("DFW Airport → Downtown Dallas","25–40 min"),("DAL Airport → Uptown","15–25 min"),
            ("Dallas → Fort Worth","45–60 min"),("DFW Airport → Plano / Frisco","30–45 min")],
    faq_extra=("Do you serve Fort Worth?",
               "Yes — the entire DFW metroplex, including Fort Worth, Arlington, Irving, and the mid-cities.")),
  "houston": dict(region="national", name="Houston", short="Houston",
    blurb="Professional chauffeur service across greater Houston — IAH and Hobby transfers, Downtown, the Galleria, and the Energy Corridor.",
    hoods="Downtown, the Galleria, the Medical Center, the Energy Corridor, and The Woodlands",
    airports="IAH (30–50 min), HOU (20–35 min)",
    routes=[("IAH Airport → Downtown","30–50 min"),("HOU Airport → Downtown","20–35 min"),
            ("Houston → The Woodlands","40–60 min"),("IAH Airport → Galleria","35–55 min")],
    faq_extra=("Do you serve the Medical Center?",
               "Yes — patient and family transport to the Texas Medical Center is a frequent request, handled with extra care.")),
  "atlanta": dict(region="national", name="Atlanta", short="Atlanta",
    blurb="Black car service for Atlanta — ATL airport transfers, Midtown, Buckhead, and corporate travel across the metro.",
    hoods="Midtown, Buckhead, Downtown, Sandy Springs, and Alpharetta",
    airports="ATL (20–40 min)",
    routes=[("ATL Airport → Midtown","20–35 min"),("ATL Airport → Buckhead","25–40 min"),
            ("Atlanta → Alpharetta","35–50 min"),("ATL Airport → Sandy Springs","30–45 min")],
    faq_extra=("How early should I book for ATL departures?",
               "Hartsfield-Jackson is the world's busiest airport — we recommend booking the night before and we'll time your pickup to traffic and security waits.")),
  "boston": dict(region="national", name="Boston", short="Boston",
    blurb="Chauffeured rides across Boston and New England — Logan transfers, Back Bay, the Seaport, and Cambridge.",
    hoods="Back Bay, the Seaport, the Financial District, Beacon Hill, and Cambridge",
    airports="BOS (15–30 min)",
    routes=[("BOS Airport → Back Bay","15–30 min"),("BOS Airport → Cambridge","20–35 min"),
            ("Boston → Providence","60–75 min"),("Boston → Cape Cod","1.5–2 hr")],
    faq_extra=("Do you serve the greater New England area?",
               "Yes — Providence, Worcester, southern New Hampshire, and Cape Cod are all within reach.")),
  "seattle": dict(region="national", name="Seattle", short="Seattle",
    blurb="Black car service for the Puget Sound — Sea-Tac transfers, Downtown, Bellevue, and the Eastside tech corridor.",
    hoods="Downtown, South Lake Union, Capitol Hill, Bellevue, Redmond, and Kirkland",
    airports="SEA (25–40 min)",
    routes=[("SEA Airport → Downtown Seattle","25–40 min"),("SEA Airport → Bellevue","30–45 min"),
            ("Seattle → Redmond","25–40 min"),("Downtown → Snoqualmie","40–55 min")],
    faq_extra=("Do you serve the Eastside?",
               "Yes — Bellevue, Redmond, Kirkland, and the entire tech corridor, including campus-to-campus runs.")),
  "washington-dc": dict(region="national", name="Washington, D.C.", short="D.C.",
    blurb="Professional chauffeur service for the capital region — DCA, IAD, and BWI transfers, Georgetown to Capitol Hill.",
    hoods="Georgetown, Capitol Hill, Dupont Circle, the National Mall area, Arlington, and Tysons",
    airports="DCA (15–25 min), IAD (40–60 min), BWI (50–70 min)",
    routes=[("DCA Airport → Downtown D.C.","15–25 min"),("IAD Airport → Georgetown","40–60 min"),
            ("BWI Airport → D.C.","50–70 min"),("D.C. → Tysons / McLean","25–40 min")],
    faq_extra=("Do you handle government and diplomatic travel?",
               "Yes — discreet, punctual service for official visits, delegations, and government contractors is a specialty.")),
  "san-diego": dict(region="national", name="San Diego", short="San Diego",
    blurb="Chauffeured rides across San Diego — airport transfers, the Gaslamp Quarter, La Jolla, and Coronado.",
    hoods="The Gaslamp Quarter, La Jolla, Del Mar, Coronado, and Carlsbad",
    airports="SAN (10–20 min)",
    routes=[("SAN Airport → Gaslamp Quarter","10–15 min"),("SAN Airport → La Jolla","20–30 min"),
            ("San Diego → Carlsbad","35–50 min"),("San Diego → Temecula Wine Country","1–1.5 hr")],
    faq_extra=("Do you go to Temecula wine country?",
               "Yes — wine country day trips with a dedicated chauffeur are available; see our Wine Tours service.")),
  "austin": dict(region="national", name="Austin", short="Austin",
    blurb="Black car service for the Texas capital — AUS transfers, downtown, the Domain, and SXSW-season logistics.",
    hoods="Downtown, South Congress, the Domain, East Austin, and West Lake Hills",
    airports="AUS (15\u201325 min)",
    routes=[("AUS Airport \u2192 Downtown Austin","15\u201325 min"),("AUS Airport \u2192 The Domain","25\u201340 min"),
            ("Austin \u2192 San Antonio","1.5 hr"),("Downtown \u2192 Hill Country wineries","45\u201360 min")],
    faq_extra=("Do you handle SXSW and festival weeks?",
               "Yes \u2014 festival weeks are our specialty. Book early; hourly charters keep a dedicated chauffeur on your schedule all day.")),
  "nashville": dict(region="national", name="Nashville", short="Nashville",
    blurb="Chauffeured rides across Music City \u2014 BNA transfers, Broadway, and group transportation for events.",
    hoods="Downtown, the Gulch, Music Row, East Nashville, and Green Hills",
    airports="BNA (15\u201325 min)",
    routes=[("BNA Airport \u2192 Downtown Nashville","15\u201325 min"),("BNA Airport \u2192 The Gulch","15\u201325 min"),
            ("Nashville \u2192 Franklin","30\u201345 min"),("Downtown \u2192 Opryland","20\u201330 min")],
    faq_extra=("Do you do bachelorette and group event transportation?",
               "Yes \u2014 our party buses and Sprinters are built for it. One flat quote for the night, one driver, zero coordination stress.")),
  "denver": dict(region="national", name="Denver", short="Denver",
    blurb="Black car service for the Mile High City \u2014 DEN transfers, downtown, Boulder, and mountain resort trips.",
    hoods="Downtown, LoDo, Cherry Creek, the Tech Center, and Boulder",
    airports="DEN (35\u201350 min)",
    routes=[("DEN Airport \u2192 Downtown Denver","35\u201350 min"),("DEN Airport \u2192 Boulder","50\u201370 min"),
            ("Denver \u2192 Vail","2 hr"),("Denver \u2192 Breckenridge","2 hr")],
    faq_extra=("Do you drive to the ski resorts?",
               "Yes \u2014 Vail, Breckenridge, Keystone, and Winter Park transfers in SUVs equipped for mountain conditions, with room for ski gear.")),
  "phoenix": dict(region="national", name="Phoenix", short="Phoenix",
    blurb="Chauffeured rides across the Valley \u2014 PHX transfers, Scottsdale, golf trips, and spring training.",
    hoods="Downtown Phoenix, Scottsdale, Paradise Valley, Tempe, and Mesa",
    airports="PHX (15\u201330 min)",
    routes=[("PHX Airport \u2192 Scottsdale","20\u201335 min"),("PHX Airport \u2192 Downtown","15\u201325 min"),
            ("Phoenix \u2192 Sedona","2 hr"),("Scottsdale \u2192 TPC Scottsdale","10\u201315 min")],
    faq_extra=("Do you handle golf outings and spring training?",
               "Yes \u2014 SUVs fit the whole foursome and clubs, and we run group shuttles for spring training and tournament weeks.")),
  "philadelphia": dict(region="national", name="Philadelphia", short="Philly",
    blurb="Black car service for Philadelphia \u2014 PHL transfers, Center City, University City, and the Main Line.",
    hoods="Center City, University City, Old City, Rittenhouse, and the Main Line",
    airports="PHL (20\u201335 min)",
    routes=[("PHL Airport \u2192 Center City","20\u201335 min"),("Philadelphia \u2192 New York City","2 hr"),
            ("PHL Airport \u2192 King of Prussia","30\u201345 min"),("Center City \u2192 Princeton","50\u201370 min")],
    faq_extra=("Do you run trips to New York or D.C.?",
               "Yes \u2014 the Northeast Corridor is a popular charter: flat-rate city-to-city rides with no train-station hassle, door to door.")),
  "orlando": dict(region="national", name="Orlando", short="Orlando",
    blurb="Chauffeured rides for Orlando \u2014 MCO transfers, theme parks, conventions, and family group travel.",
    hoods="Downtown, Lake Nona, Winter Park, the convention district, and the theme park corridors",
    airports="MCO (20\u201340 min)",
    routes=[("MCO Airport \u2192 Walt Disney World area","25\u201340 min"),("MCO Airport \u2192 Universal area","20\u201330 min"),
            ("MCO Airport \u2192 Convention Center","20\u201330 min"),("Orlando \u2192 Tampa","1.5 hr")],
    faq_extra=("Do you provide car seats for kids?",
               "Yes \u2014 request car seats or boosters when booking and we'll have them installed before pickup. Family travel is a big part of what we do in Orlando.")),
  "charlotte": dict(region="national", name="Charlotte", short="Charlotte",
    blurb="Black car service for Charlotte \u2014 CLT transfers, Uptown, South End, and corporate banking travel.",
    hoods="Uptown, South End, Dilworth, Ballantyne, and Lake Norman",
    airports="CLT (15\u201325 min)",
    routes=[("CLT Airport \u2192 Uptown","15\u201325 min"),("CLT Airport \u2192 Ballantyne","25\u201340 min"),
            ("Charlotte \u2192 Lake Norman","30\u201345 min"),("Uptown \u2192 Concord","30\u201340 min")],
    faq_extra=("Do you serve corporate banking travel?",
               "Yes \u2014 Charlotte's financial sector is a core clientele: consistent, discreet service with account billing for teams.")),
  "minneapolis": dict(region="national", name="Minneapolis", short="MSP",
    blurb="Chauffeured rides for the Twin Cities \u2014 MSP transfers, downtown Minneapolis, St. Paul, and corporate travel.",
    hoods="Downtown Minneapolis, St. Paul, Edina, Bloomington, and the North Loop",
    airports="MSP (15\u201330 min)",
    routes=[("MSP Airport \u2192 Downtown Minneapolis","15\u201325 min"),("MSP Airport \u2192 St. Paul","15\u201325 min"),
            ("MSP Airport \u2192 Mall of America","10\u201315 min"),("Minneapolis \u2192 Rochester (Mayo Clinic)","1.5 hr")],
    faq_extra=("Do you do Mayo Clinic transfers?",
               "Yes \u2014 Rochester runs for patients and families are a frequent request, handled with care and flexible timing.")),

  "portland": dict(region="national", name="Portland", short="Portland",
    blurb="Black car service in Portland — PDX transfers, downtown, and Willamette Valley wine country runs.",
    hoods="Downtown, the Pearl District, Nob Hill, Lake Oswego, and Beaverton",
    airports="PDX (20–35 min)",
    routes=[("PDX Airport → Downtown Portland","20–35 min"),("Portland → Willamette Valley","45–75 min"),
            ("Downtown → Beaverton / Nike","20–30 min"),("Portland → The Gorge","40–60 min")],
    faq_extra=("Do you run Willamette Valley wine tours from Portland?",
      "Yes — hourly charters to Dundee Hills, McMinnville, and beyond are one of our most popular Portland services.")),
  "sacramento": dict(region="national", name="Sacramento", short="Sacramento",
    blurb="Black car service in Sacramento — SMF transfers, Capitol business travel, and Bay Area connections.",
    hoods="Downtown, Midtown, East Sacramento, Folsom, and Roseville",
    airports="SMF (20–30 min)",
    routes=[("SMF Airport → Downtown","20–30 min"),("Sacramento → San Francisco","1.5–2 hr"),
            ("Capitol → Folsom","25–40 min"),("Sacramento → Napa Valley","1–1.5 hr")],
    faq_extra=("Do you do Sacramento to Bay Area transfers?",
      "Constantly — flat-rate sedan and SUV runs to San Francisco, Oakland, and Silicon Valley, often beating the hassle of flying.")),
  "new-orleans": dict(region="national", name="New Orleans", short="NOLA",
    blurb="Black car service in New Orleans — MSY transfers, French Quarter, Garden District, and event travel.",
    hoods="the French Quarter, Garden District, Warehouse District, Uptown, and Metairie",
    airports="MSY (25–40 min)",
    routes=[("MSY Airport → French Quarter","25–40 min"),("MSY → Garden District","25–35 min"),
            ("Quarter → Convention Center","10–15 min"),("New Orleans → Baton Rouge","1.25–1.5 hr")],
    faq_extra=("Can you handle Mardi Gras and festival dates?",
      "Yes — book early for Mardi Gras, Jazz Fest, and Essence. Our chauffeurs know the parade-route closures and the workarounds.")),
  "tampa": dict(region="national", name="Tampa", short="Tampa",
    blurb="Black car service in Tampa Bay — TPA transfers, downtown, St. Pete, and Clearwater beach runs.",
    hoods="Downtown, Hyde Park, Westshore, St. Petersburg, and Clearwater",
    airports="TPA (15–25 min)",
    routes=[("TPA Airport → Downtown Tampa","15–25 min"),("TPA → St. Petersburg","25–40 min"),
            ("Tampa → Clearwater Beach","35–50 min"),("Downtown → Wesley Chapel","30–45 min")],
    faq_extra=("Do you cover both sides of the bay?",
      "Yes — Tampa, St. Pete, and Clearwater are all home turf, including cruise terminal pickups at Port Tampa Bay.")),
  "detroit": dict(region="national", name="Detroit", short="Detroit",
    blurb="Black car service in Detroit — DTW transfers, downtown, Birmingham, and automotive corporate travel.",
    hoods="Downtown, Midtown, Birmingham, Royal Oak, and Dearborn",
    airports="DTW (25–40 min)",
    routes=[("DTW Airport → Downtown Detroit","25–40 min"),("DTW → Birmingham","30–45 min"),
            ("Downtown → Ann Arbor","45–60 min"),("Detroit → Auburn Hills","35–50 min")],
    faq_extra=("Do you serve automotive industry travel?",
      "Extensively — plant visits, supplier meetings, and auto show season are core Detroit work, with account billing for teams.")),
  "salt-lake-city": dict(region="national", name="Salt Lake City", short="SLC",
    blurb="Black car service in Salt Lake City — SLC transfers, downtown, and ski resort runs to Park City and the Cottonwoods.",
    hoods="Downtown, Sugar House, the Avenues, Park City, and Cottonwood Heights",
    airports="SLC (10–20 min)",
    routes=[("SLC Airport → Downtown","10–20 min"),("SLC → Park City","35–50 min"),
            ("SLC → Snowbird / Alta","40–60 min"),("SLC → Deer Valley","40–55 min")],
    faq_extra=("Do you do ski transfers with gear?",
      "All winter long — SUVs fit the whole group plus skis and boards, and chauffeurs run the canyons in all conditions.")),
  "san-antonio": dict(region="national", name="San Antonio", short="San Antonio",
    blurb="Black car service in San Antonio — SAT transfers, River Walk, the Pearl, and Hill Country runs.",
    hoods="Downtown and the River Walk, the Pearl, Alamo Heights, Stone Oak, and La Cantera",
    airports="SAT (10–20 min)",
    routes=[("SAT Airport → River Walk","10–20 min"),("SAT → La Cantera","20–30 min"),
            ("San Antonio → Hill Country wineries","45–75 min"),("San Antonio → Austin","1.25–1.5 hr")],
    faq_extra=("Do you run Hill Country wine tours from San Antonio?",
      "Yes — Fredericksburg and the 290 wine corridor are an easy day trip with a dedicated chauffeur.")),
  "raleigh": dict(region="national", name="Raleigh", short="Raleigh",
    blurb="Black car service in Raleigh-Durham — RDU transfers, Research Triangle corporate travel, and university runs.",
    hoods="Downtown Raleigh, North Hills, Durham, Chapel Hill, and Cary",
    airports="RDU (15–25 min)",
    routes=[("RDU Airport → Downtown Raleigh","15–25 min"),("RDU → Durham","15–25 min"),
            ("RDU → Chapel Hill","20–30 min"),("Raleigh → Research Triangle Park","15–25 min")],
    faq_extra=("Do you serve the whole Research Triangle?",
      "Yes — Raleigh, Durham, Chapel Hill, and RTP are all covered, with account billing for recurring corporate travel.")),
}

AIRPORTS = {
  "sfo": dict(code="SFO", name="San Francisco International Airport",
    blurb="Meet-and-greet pickups, live flight tracking, and flat rates from SFO to anywhere in the Bay Area.",
    terminals="Harvey Milk Terminal 1, Terminal 2, Terminal 3, and the International Terminal",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("SFO → Downtown San Francisco","25–35 min"),("SFO → Palo Alto / Menlo Park","30–40 min"),
            ("SFO → San Jose","45–60 min"),("SFO → Napa Valley","1.5–2 hr")]),
  "oak": dict(code="OAK", name="Oakland International Airport",
    blurb="Skip the rideshare lot chaos — your chauffeur meets you at arrivals with your name on a sign.",
    terminals="Terminal 1 and Terminal 2",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("OAK → Downtown Oakland","15–20 min"),("OAK → San Francisco","30–40 min"),
            ("OAK → Berkeley","20–25 min"),("OAK → Walnut Creek","30–40 min")]),
  "sjc": dict(code="SJC", name="San José Mineta International Airport",
    blurb="Silicon Valley's airport, handled properly — flight-tracked pickups and flat-rate rides across the South Bay.",
    terminals="Terminal A and Terminal B",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("SJC → Downtown San Jose","10–15 min"),("SJC → Palo Alto","25–35 min"),
            ("SJC → Santana Row","10–15 min"),("SJC → San Francisco","50–70 min")]),
  # ---- Nationwide ----
  "jfk": dict(code="JFK", name="John F. Kennedy International Airport",
    blurb="New York's biggest gateway, without the taxi-line chaos — flight-tracked curbside pickup and a flat rate into Manhattan.",
    terminals="Terminals 1, 4, 5, 7 and 8",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("JFK → Midtown Manhattan","45–75 min"),("JFK → Brooklyn","30–50 min"),
            ("JFK → LaGuardia (LGA)","20–30 min"),("JFK → Newark (EWR)","60–90 min")]),
  "lga": dict(code="LGA", name="LaGuardia Airport",
    blurb="The business traveler's airport — quick into Midtown, and your chauffeur is tracking the shuttle-hop delays so you don't have to.",
    terminals="Terminals A, B and C",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("LGA → Midtown Manhattan","25–45 min"),("LGA → Upper East Side","20–35 min"),
            ("LGA → Brooklyn","35–55 min"),("LGA → JFK","20–30 min")]),
  "ewr": dict(code="EWR", name="Newark Liberty International Airport",
    blurb="Often the smartest way into Manhattan — and with a chauffeur waiting, the Jersey side stops feeling like a detour.",
    terminals="Terminals A, B and C",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("EWR → Midtown Manhattan","30–60 min"),("EWR → Jersey City","15–25 min"),
            ("EWR → Hoboken","20–30 min"),("EWR → Brooklyn","45–75 min")]),
  "lax": dict(code="LAX", name="Los Angeles International Airport",
    blurb="LAX traffic is a fact of life — a flight-tracked chauffeur with a planned route is how you beat it.",
    terminals="all nine terminals, including Tom Bradley International",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("LAX → Santa Monica","20–40 min"),("LAX → Beverly Hills","25–50 min"),
            ("LAX → Downtown LA","30–60 min"),("LAX → Burbank","45–75 min")]),
  "ord": dict(code="ORD", name="Chicago O'Hare International Airport",
    blurb="One of the world's busiest airports, handled calmly — flight-tracked pickup, flat rate into the Loop.",
    terminals="Terminals 1, 2, 3 and 5",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("ORD → The Loop","40–70 min"),("ORD → River North","35–60 min"),
            ("ORD → Evanston","30–45 min"),("ORD → Midway (MDW)","45–70 min")]),
  "mdw": dict(code="MDW", name="Chicago Midway International Airport",
    blurb="Closer to downtown than O'Hare and faster to clear — with your car already curbside.",
    terminals="the main terminal, Concourses A, B and C",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("MDW → The Loop","20–35 min"),("MDW → West Loop","20–30 min"),
            ("MDW → O'Hare (ORD)","45–70 min"),("MDW → Oak Brook","30–45 min")]),
  "mia": dict(code="MIA", name="Miami International Airport",
    blurb="From jet bridge to Brickell or the beach — a flight-tracked pickup and a cool, quiet ride out of the humidity.",
    terminals="Concourses D through J across the North, Central and South terminals",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("MIA → South Beach","20–35 min"),("MIA → Brickell","15–25 min"),
            ("MIA → Coral Gables","15–20 min"),("MIA → Fort Lauderdale","35–55 min")]),
  "las": dict(code="LAS", name="Harry Reid International Airport",
    blurb="Minutes from the Strip — start the trip properly with a chauffeur at arrivals instead of a rideshare scrum.",
    terminals="Terminals 1 and 3",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("LAS → The Strip","10–20 min"),("LAS → Downtown / Fremont","15–25 min"),
            ("LAS → Summerlin","25–35 min"),("LAS → Henderson","20–30 min")]),
  "den": dict(code="DEN", name="Denver International Airport",
    blurb="DEN sits far from everything — which is exactly why a flat-rate chauffeur beats the alternatives, downtown or up the mountain.",
    terminals="Jeppesen Terminal with Concourses A, B and C",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("DEN → Downtown Denver","30–45 min"),("DEN → Cherry Creek","30–45 min"),
            ("DEN → Boulder","45–60 min"),("DEN → Vail","1.75–2.5 hr")]),
  "dfw": dict(code="DFW", name="Dallas Fort Worth International Airport",
    blurb="Bigger than Manhattan and easy to get lost in — your chauffeur knows exactly which terminal and which door.",
    terminals="Terminals A through E",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("DFW → Downtown Dallas","25–40 min"),("DFW → Uptown","25–40 min"),
            ("DFW → Fort Worth","25–40 min"),("DFW → Plano / Frisco","30–50 min")]),
  "dal": dict(code="DAL", name="Dallas Love Field",
    blurb="The quick in-and-out option minutes from Uptown — perfect for the day-trip business flyer.",
    terminals="the main terminal, 20 gates",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("DAL → Downtown Dallas","10–20 min"),("DAL → Uptown","10–15 min"),
            ("DAL → DFW Airport","20–30 min"),("DAL → Las Colinas","15–25 min")]),
  "iah": dict(code="IAH", name="George Bush Intercontinental Airport",
    blurb="Houston''s international hub — flight-tracked pickups and flat rates across a city built on distance.",
    terminals="Terminals A through E",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("IAH → Downtown Houston","25–45 min"),("IAH → The Galleria","30–50 min"),
            ("IAH → Energy Corridor","35–60 min"),("IAH → Hobby (HOU)","35–55 min")]),
  "hou": dict(code="HOU", name="William P. Hobby Airport",
    blurb="Houston''s close-in airport — fast to clear, and even faster to leave with a chauffeur curbside.",
    terminals="the central terminal",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("HOU → Downtown Houston","20–30 min"),("HOU → The Galleria","25–40 min"),
            ("HOU → Texas Medical Center","15–25 min"),("HOU → IAH","35–55 min")]),
  "aus": dict(code="AUS", name="Austin-Bergstrom International Airport",
    blurb="Festival weeks turn AUS pickups into a contact sport — a pre-booked chauffeur is the cheat code.",
    terminals="the Barbara Jordan Terminal",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("AUS → Downtown Austin","15–25 min"),("AUS → South Congress","10–20 min"),
            ("AUS → The Domain","25–40 min"),("AUS → Round Rock","30–45 min")]),
  "atl": dict(code="ATL", name="Hartsfield-Jackson Atlanta International Airport",
    blurb="The world''s busiest airport rewards a plan — a flight-tracked pickup straight to the car.",
    terminals="the domestic and international terminals, Concourses A through F",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("ATL → Downtown Atlanta","15–25 min"),("ATL → Midtown","20–30 min"),
            ("ATL → Buckhead","25–40 min"),("ATL → Alpharetta","40–60 min")]),
  "bos": dict(code="BOS", name="Boston Logan International Airport",
    blurb="Minutes from downtown through the harbor tunnels — with a chauffeur who already knows which one is moving.",
    terminals="Terminals A, B, C and E",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("BOS → Back Bay","15–30 min"),("BOS → Financial District","10–20 min"),
            ("BOS → Cambridge","20–35 min"),("BOS → Seaport","10–15 min")]),
  "iad": dict(code="IAD", name="Washington Dulles International Airport",
    blurb="The international gateway to the capital — long corridors, then a quiet car waiting at arrivals.",
    terminals="the main terminal with Concourses A through D",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("IAD → Downtown DC","35–55 min"),("IAD → Tysons","20–30 min"),
            ("IAD → Arlington","30–45 min"),("IAD → Reston","15–20 min")]),
  "dca": dict(code="DCA", name="Ronald Reagan Washington National Airport",
    blurb="Across the river from the District — the closest thing to landing downtown, made even faster with a car waiting.",
    terminals="Terminals 1 and 2",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("DCA → Capitol Hill","10–20 min"),("DCA → Downtown DC","10–20 min"),
            ("DCA → Georgetown","15–25 min"),("DCA → Bethesda","25–40 min")]),
  "san": dict(code="SAN", name="San Diego International Airport",
    blurb="Land practically downtown — and keep that easy San Diego pace going with a chauffeur at the curb.",
    terminals="Terminals 1 and 2",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("SAN → Gaslamp Quarter","10–15 min"),("SAN → La Jolla","20–30 min"),
            ("SAN → Coronado","10–20 min"),("SAN → Del Mar","25–35 min")]),
  "phl": dict(code="PHL", name="Philadelphia International Airport",
    blurb="Quick run up I-95 to Center City — flight-tracked, flat-rate, and no taxi-line gamble.",
    terminals="Terminals A through F",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("PHL → Center City","20–30 min"),("PHL → University City","15–25 min"),
            ("PHL → King of Prussia","30–45 min"),("PHL → Cherry Hill","25–35 min")]),
  "phx": dict(code="PHX", name="Phoenix Sky Harbor International Airport",
    blurb="America''s friendliest mega-airport, minutes from downtown — and a cool car waiting matters in the desert.",
    terminals="Terminals 3 and 4",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("PHX → Downtown Phoenix","10–15 min"),("PHX → Scottsdale","20–35 min"),
            ("PHX → Tempe","10–15 min"),("PHX → Mesa","25–35 min")]),
  "clt": dict(code="CLT", name="Charlotte Douglas International Airport",
    blurb="A banking-town airport that runs on schedules — your chauffeur keeps yours intact.",
    terminals="the main terminal, Concourses A through E",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("CLT → Uptown Charlotte","15–25 min"),("CLT → South End","15–25 min"),
            ("CLT → Ballantyne","25–40 min"),("CLT → Lake Norman","35–50 min")]),
  "bna": dict(code="BNA", name="Nashville International Airport",
    blurb="Eight minutes of guitar at baggage claim, then straight to Broadway — or past it, if you''ve been before.",
    terminals="the main terminal, Concourses A through D",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("BNA → Downtown / Broadway","15–25 min"),("BNA → The Gulch","15–25 min"),
            ("BNA → Music Row","20–30 min"),("BNA → Franklin","30–45 min")]),
  "msp": dict(code="MSP", name="Minneapolis–Saint Paul International Airport",
    blurb="Between both downtowns and next to the Mall of America — a chauffeur makes the Twin Cities feel like one.",
    terminals="Terminal 1 (Lindbergh) and Terminal 2 (Humphrey)",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("MSP → Downtown Minneapolis","20–30 min"),("MSP → Downtown St. Paul","15–25 min"),
            ("MSP → Mall of America","10–15 min"),("MSP → Edina","20–30 min")]),
  "mco": dict(code="MCO", name="Orlando International Airport",
    blurb="Start the family trip calm — car seats arranged, luggage handled, straight to the resort gates.",
    terminals="Terminals A, B and C",
    wait="30 minutes free on domestic arrivals, 1 hour free on international",
    routes=[("MCO → Walt Disney World","25–40 min"),("MCO → Universal / I-Drive","20–35 min"),
            ("MCO → Downtown Orlando","20–30 min"),("MCO → Winter Park","25–40 min")]),
}

WINE_REGIONS = {
  # ---- California ----
  "napa-valley": dict(area="ca", name="Napa Valley",
    drive="about 1.5 hours from San Francisco",
    known="Cabernet Sauvignon estates along Highway 29 and the quieter Silverado Trail",
    towns="Yountville, St. Helena, and Calistoga",
    faq=("How many Napa wineries can we visit in a day?",
         "Three to four is the sweet spot — morning tasting, a long Yountville lunch, then two relaxed afternoon stops. Your chauffeur keeps the day on pace without rushing it.")),
  "sonoma": dict(area="ca", name="Sonoma",
    drive="about 1 to 1.5 hours from San Francisco",
    known="Pinot Noir and Chardonnay producers around the historic Sonoma Plaza",
    towns="Sonoma, Glen Ellen, and Kenwood",
    faq=("Napa or Sonoma — which should we choose?",
         "Napa is polish and grand estates; Sonoma is charm and family producers around a walkable square. They're 30 minutes apart — many of our tours do one of each.")),
  "healdsburg": dict(area="ca", name="Healdsburg",
    drive="about 1.5 to 2 hours from San Francisco",
    known="Dry Creek Zinfandel and Russian River Pinot Noir",
    towns="Healdsburg square, Dry Creek Valley, and the Russian River Valley",
    faq=("Is Healdsburg worth the longer drive?",
         "If you've already done Napa and Sonoma, absolutely — smaller crowds, tasting-room conversations with actual winemakers, and one of the best small towns in California.")),
  "paso-robles": dict(area="ca", name="Paso Robles",
    drive="on the Central Coast, about 3.5 hours from the Bay Area or LA",
    known="bold Rhône-style blends and a fast-rising food scene",
    towns="downtown Paso Robles and the Adelaida District",
    faq=("Can we do Paso Robles as a day trip?",
         "From the Bay Area or LA it's better as an overnight — we arrange multi-day charters with your chauffeur staying with the trip.")),
  "santa-ynez": dict(area="ca", name="Santa Ynez Valley",
    drive="about 45 minutes from Santa Barbara, 2.5 hours from LA",
    known="Pinot Noir and Syrah in Santa Barbara wine country",
    towns="Los Olivos, Solvang, and Santa Ynez",
    faq=("What's the best home base for Santa Ynez tasting?",
         "Los Olivos packs dozens of tasting rooms into a few walkable blocks — ideal for a no-driving afternoon — while estate visits spread through the valley.")),
  "livermore": dict(area="ca", name="Livermore Valley",
    drive="just 30 to 45 minutes from most of the East Bay",
    known="one of California's oldest wine regions, minutes from the Bay",
    towns="Livermore and the Tesla Road corridor",
    faq=("Is Livermore good for a short-notice wine day?",
         "It's the Bay Area's best-kept secret for exactly that — close enough for an afternoon escape with no hotel required.")),
  "temecula": dict(area="ca", name="Temecula Valley",
    drive="about an hour from San Diego, 1.5 from Orange County",
    known="Southern California's wine country, with hot-air balloons at dawn",
    towns="Old Town Temecula and the De Portola Wine Trail",
    faq=("What pairs well with a Temecula wine tour?",
         "Sunrise balloon rides — many groups do balloon-then-brunch-then-tastings. We coordinate the whole loop with one vehicle.")),
  # ---- Nationwide ----
  "willamette-valley": dict(area="us", name="Willamette Valley",
    drive="about an hour from Portland, Oregon",
    known="world-class Pinot Noir from Dundee Hills and McMinnville",
    towns="Dundee, McMinnville, and Newberg",
    faq=("When is the best time to visit the Willamette Valley?",
         "Late summer through harvest (August–October) is magic, but tasting rooms are welcoming year-round — winter visits mean winemakers have time to talk.")),
  "walla-walla": dict(area="us", name="Walla Walla",
    drive="in southeast Washington, with direct flights from Seattle",
    known="powerhouse Syrah and Cabernet from over 120 wineries",
    towns="downtown Walla Walla and the airport district incubators",
    faq=("How walkable is Walla Walla wine tasting?",
         "Downtown has dozens of tasting rooms within blocks, but the estate vineyards in the Rocks District and SeVein need a driver — that's where we come in.")),
  "finger-lakes": dict(area="us", name="Finger Lakes",
    drive="about 1.5 hours from Rochester or Syracuse, New York",
    known="America's best Riesling along Seneca and Keuka Lakes",
    towns="Geneva, Hammondsport, and Watkins Glen",
    faq=("Which lake should we tour first?",
         "Seneca Lake has the greatest density of wineries; Keuka the prettiest setting. A chauffeured day can comfortably loop one lake — not both.")),
  "texas-hill-country": dict(area="us", name="Texas Hill Country",
    drive="about an hour from Austin or San Antonio",
    known="Tempranillo and Viognier along the Fredericksburg Wine Road",
    towns="Fredericksburg, Johnson City, and Driftwood",
    faq=("How far apart are Hill Country wineries?",
         "Spread out — Highway 290's wineries span 30+ miles, which is exactly why a designated chauffeur beats ride-hailing between stops out there.")),
  "virginia": dict(area="us", name="Virginia Wine Country",
    drive="under an hour from Washington, D.C.",
    known="Viognier and Bordeaux-style blends in Loudoun County and around Charlottesville",
    towns="Middleburg, Purcellville, and Charlottesville",
    faq=("Can we do Virginia wine country as a D.C. day trip?",
         "Easily — Loudoun County's tasting rooms start 45 minutes from the District. Charlottesville's Monticello trail is better with an early start or an overnight.")),
}
